# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tUK29CN8Ye6Bi_8Dta-Vk8lUmEfHmrN9
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set plot style for better asthetics
sns.set(style='whitegrid')

# Data Loading
df = pd.read_csv('/content/healthcare_dataset.csv', encoding='latin-1', on_bad_lines='skip')

df.head()

"""In Original datasheat "**Stay Days**" and "**Age Group**" was missing.As per the Client demand, we have added 2 more coloumn for best results."""

print("\nDescriptive Statistics:")
df.describe()

"""**Interpretation of of .describe() fn:**  
1.  **Age**:-The age ranges from 13 years to 89 years, with an average age of about 52 years of getting admitted in hospital.
2.  **Billing Amount**:- The **Minimum billing amount is in negative** meaning refund is initiated to costomer and maximum billing amount is **52764.27$** with average billing amount **25538.06** dollar.

1.  **Stays Days**:- The Stays Days ranges from1-30 days with average of **15** days






"""

df.info()

"""The entire Data was in **Object** data types so in order to perforn Data Cleaning and Operations,I have changed Age,Room Number and Billing amount into **respective data type** and Date of Admission and Discharge date in **daytime data type**"""

df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
df['Billing Amount'] = pd.to_numeric(df['Billing Amount'], errors='coerce')
df['Room Number'] = pd.to_numeric(df['Room Number'], errors='coerce')
df['Date of Admission'] = pd.to_datetime(df['Date of Admission'], errors='coerce')
df['Discharge Date'] = pd.to_datetime(df['Discharge Date'], errors='coerce')

df.info()

df.isnull().sum()

"""There is no null value to handle throughout the entire datashet

**UNIVARIATE ANALYSIS**



 **Theoretical Concept**:
This is the simplest form of data analysis, where the data being analyzed contains only one variable. The main purpose is to describe the data and find patterns within it.





* For Numerical Variables: We use histograms (histplot) or kernel density plots (kdeplot) to understand the distribution, and box plots (boxplot) to identify the central tendency, spread, and outliers.


*   For Categorical Variables: We use frequency tables, bar charts (countplot), or pie charts to see the count or proportion of each category.
"""

# Checking Age distribution
plt.figure(figsize=(8,5))
sns.histplot(data=df, x='Age', kde=True, bins=30)
plt.title('Age Distribution with KDE')
plt.show()

"""The dataset shows a nearly uniform distribution of adult patients aged **20–80**, indicating the hospital serves a wide adult population without a dominant age category."""

# checking Billing distribution
sns.histplot(data=df, x='Billing Amount',bins=30, kde=True)
plt.title('Billing Amount Distribution with KDE')
plt.show()

"""The billing distribution is broad and uniformly spread across ₹0–50,000, indicating that the hospital manages a balanced mix of low, mid, and high-cost cases. The **KDE curve suggests no dominant billing category**, reflecting a diverse case mix. Very low and very high billing amounts occur less frequently, which aligns with typical treatment patterns."""

# Checking Outliers
Q1=df['Billing Amount'].quantile(0.25)
Q3=df['Billing Amount'].quantile(0.75)
IQR= Q3-Q1
print(IQR)
lower_bound=Q1-1.5*IQR
upper_bound=Q3+1.5*IQR
print(lower_bound)
print(upper_bound)
outliers=df[(df['Billing Amount']<lower_bound) | (df['Billing Amount']>upper_bound)]
outliers.head()

"""Using the **IQR method**, **no significant billing outliers were detected** because the calculated lower bound is negative and the upper bound is very high (~$74,689). All billing entries fall within this range, indicating that the billing distribution is uniformly spread without extreme anomalies. Any negative billing values, if present, would represent refunds or data-entry issues rather than true outliers."""



"""Generate summary statistics (mean age, billing average, condition counts).

Identify most common diseases and their patient age distribution.

Analyze hospital-wise patient count & average billing.

Compare billing amount between Admission Types (Urgent vs Emergency vs Elective).

Find average hospital stay duration per disease type.

**Descriptive Statistics** :-
Display summary statistics (mean, min, max, std) for the numerical columns.
"""

# Descriptive Statistics
Age=df['Age'].mean()
Age=round(Age)
print  ("Mean Age is:",Age)
BA=df['Billing Amount'].mean().round(3)
print("Mean Billing Amount is:",BA)
CC=df['Medical Condition'].value_counts()
df.sort_values(by='Medical Condition', ascending=False)
print(CC)
plt.title('Medical Condition Distribution')
sns.barplot(x=CC.index, y=CC.values,hue=CC.index)

"""*  The average age is **52** for getting admitted in hospital.

* The average Billing Amount per person is : **25539.316**$.  

* The medical condition distribution is evenly balanced across Arthritis, Diabetes, Hypertension, Obesity, Cancer, and Asthma, with each condition having approximately 9,200–9,300 patients. But Out of all **Arthritis have most patient as compare with other medical condition.**

**BIVARIATE ANALYSIS**
"""

# Hospital wise patient count and Avg Billing
Pc=df['Hospital'].value_counts()
avg_billing = df.groupby('Hospital')['Billing Amount'].mean().round(2)
avg_billing
result = pd.concat([Pc, avg_billing], axis=1)
result.columns = ['Pc', 'AvgBilling']
result

"""
1.   **High Volume Hospitals:-**


*   These hospitals have moderate and consistent billing averages, suggesting standardized procedures and potentially higher operational efficiency
*   Their patient load indicates strong demand and possibly broader service offerings

2.   **Low-Volume Hospitals**

*   These hospitals display high variability in billing amounts, often much higher than high-volume hospitals.
* This may indicate:

    1.   Specialized treatments

    2. Limited service offerings

*   Due to limited patient count, these values should be interpreted cautiously.


"""

# Avs billing amount with Admission Type
Admission_type_Billing=df.groupby('Admission Type')['Billing Amount'].mean().round(2)
print(Admission_type_Billing)
plt.title('Admission Type vs Billing Amount')
sns.barplot(x=Admission_type_Billing.index, y=Admission_type_Billing.values, hue=Admission_type_Billing.values)

"""The average billing amounts for Elective, Emergency, and Urgent admissions are **nearly identical**, indicating that admission type does not significantly influence billing in this dataset. **Elective cases show a slightly higher average cost**, but the overall variation is minimal, suggesting a standardized or synthetic billing structure."""

# Finding Stays Days with diffrent medical conditions.
df['Stay Days'] = (df['Discharge Date'] - df['Date of Admission']).dt.days
Average_stay_duration = df.groupby('Medical Condition')['Stay Days'].mean().round()
print(Average_stay_duration)
plt.title('Medical Condition vs Average Stay Duration')
sns.barplot(x=Average_stay_duration.index, y=Average_stay_duration.values, hue=Average_stay_duration.values)

"""*   The average length of stay is remarkably consistent across all medical conditions, ranging only between **15** **and** **16** **days**.
*  The **slightly** **higher** stay duration for **Arthritis** and **Asthma** suggests marginally more intensive care needs.

Which Medical Condition contributes to maximum revenue?

Identify high-cost and low-cost hospitals.

Patient insurance provider distribution analysis.

Which medications are prescribed most frequently and for which conditions.

Gender-wise & age-wise patient segmentation for resource planning.
"""

# Total billing amount with medical conditions.
Medical_condition_Maxm_revenue=df.groupby('Medical Condition')['Billing Amount'].sum().round(1)
print(Medical_condition_Maxm_revenue)
plt.title('Medical Condition vs Total Billing')
Medical_condition_Maxm_revenue.plot(kind='pie', autopct='%1.1f%%',startangle=90, labels=None)
plt.legend(Medical_condition_Maxm_revenue.index, title='Medical Condition', bbox_to_anchor=(1.05, 0.5), loc='center left')

"""

*   All medical conditions contribute almost equally to total billing
Each condition accounts for approximately:
16.4% to 16.8% of total billing

    This means no single medical condition dominates revenue generation for the hospital.
*   **Slightly** **higher** billing for **Diabetes** and **Obesity**.

          Patient counts per condition are nearly equal

          Total billing per condition is also nearly equal
"""

Hcost_and_Lcost=df.groupby('Hospital')['Billing Amount'].sum().round(1)

df_clean = df[df['Billing Amount'] > 0]
df_clean
hospital_cost = df_clean.groupby('Hospital')['Billing Amount'].mean().round(2)
hospital_cost_sorted = hospital_cost.sort_values(ascending=False)
high_cost = hospital_cost_sorted.head(5)
low_cost = hospital_cost_sorted.tail(5)
print(high_cost)
print(low_cost)

# Visualising High Cost and Low cost Hospitals.
import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=( 12, 6))
axes[0].pie(high_cost,labels=None,autopct='%1.1f%%',startangle=90)
axes[0].set_title('High-Cost Hospitals')
axes[0].axis('equal')
axes[0].legend( high_cost.index, title='Hospital', bbox_to_anchor=(1.05, 0.5), loc='center left')

# Low-cost hospitals pie
axes[1].pie( low_cost, labels=None,autopct='%1.1f%%',startangle=90)
axes[1].set_title('Low-Cost Hospitals')
axes[1].axis('equal')
axes[1].legend(low_cost.index,title='Hospital',bbox_to_anchor=(1.05, 0.5),loc='center left')

plt.tight_layout()
plt.show()

"""

*  High-cost hospitals (e.g., Hernandez-Morton, Walker-Garcia, Ruiz-Anthony, George-Gonzalez, Rocha-Carter) each contribute around **20**% of **total high-cost billing**.

        Billing amounts among the top hospitals are almost identical.

        No hospital stands out as a major billing driver among the high-cost group.

   This indicates a balanced distribution of expensive treatments across multiple hospitals.
*   Low-cost hospitals (e.g., Rowe, Stone and Patterson; Wilcox, Parker and White; Allen-Allen; Hebert-Wells; Perez Hoover, Moore and …) show a much more diverse distribution:

         The highest contributor (Rowe, Stone and Patterson) accounts for ~30.6%

         The lowest contributor (Perez Hoover, Moore and …) accounts for ~5.7%

          The remaining hospitals fall between 14–29%
  
     Some hospitals perform a significantly higher volume of low-cost procedures.

     Others contribute very little, indicating:

     Fewer low-cost cases

      *   Limited operations
      *   Specialized roles

"""

# Patient Count per Insurance Provider.
fig, axes = plt.subplots(1, 2, figsize=(12,6))

Paties_insurence_provider = df['Insurance Provider'].value_counts()

Paties_insurence_provider.plot( ax=axes[0],kind='pie', autopct='%1.1f%%',labels=None,startangle=90)
axes[0].set_title("Insurance Provider Share")
axes[0].legend(Paties_insurence_provider.index, loc='center left', bbox_to_anchor=(1, 0.5))
axes[0].set_ylabel("")


Paties_insurence_provider.plot(ax=axes[1],kind='bar')
axes[1].set_title("Insurance Provider Count")
axes[1].set_ylabel("Patients Count")
axes[1].set_xlabel("Insurance Provider")

plt.tight_layout()
plt.show()

"""All insurance providers—Cigna, Medicare, UnitedHealthcare, Blue Cross, and Aetna—contribute nearly equal shares of patients (each around 20%).
**Cigna has more no of patients as compare to other insurance providers**.

"""

# Most common medical condition for each medications.
medical_condition=df.groupby('Medication')['Medical Condition'].value_counts().reset_index(name='Count')

most_common_condition = (
    medical_condition.sort_values(['Medication','Count'], ascending=[True,False])
                  .drop_duplicates('Medication')
)

print(most_common_condition)

sns.barplot(x='Medication', y='Count', hue='Medical Condition', data=most_common_condition)
plt.title('Most Common Medical Condition for Each Medication')
plt.xticks(rotation=90)
plt.tight_layout()

plt.show()

"""From the above barplot we can say the most common medicine is **Lipitor which is used for Cancer patients and Aspirin used for Aethritis Patients**."""

# Male To Female
kf=df['Gender'].value_counts()
plt.title('Gender Distribution')
sns.barplot(x=kf.index, y=kf.values,hue=kf.values)
plt.tight_layout()
plt.show()

"""The Male to Female ration is almost identical only **44** patients is more hospitalised than female \"""

# Gender wise Most common medical conditions.
Gender_with_most_cases=df.groupby('Gender')['Medical Condition'].value_counts().reset_index(name='Count')
print(Gender_with_most_cases)
plt.title('Gender wise Most common medical conditions')
sns.barplot(x='Gender',y='Count', data=Gender_with_most_cases,hue='Medical Condition')
plt.legend(title='Medical Condition', bbox_to_anchor=(1.05,1), loc='upper left')
plt.tight_layout()
plt.show()

"""*   In **Female Arthritis is the most common Medical conditions**.
*   In **Male Diabetes is the most common Medical Conditions**.

0–18 (children)

19–35 (young adults)

36–50 (middle-aged)

51–70 (older adults)

70+ (senior)
"""

# Age wise patients contributions.
Age_group = df['Age'].apply(lambda x: 'Children' if x <= 18 else ('Young Adults' if x <= 35 else ('Middle-Aged' if x <=50 else ('Older Adults' if x <= 70 else 'Senior'))))
print(Age_group)
df['Age Group'] = Age_group

fig, axes = plt.subplots(1, 2, figsize=(15,6))
plt.subplots_adjust(wspace=0.4)
plt.title('Age Group Distribution')
sns.barplot(ax=axes[0],x=Age_group.value_counts().index, y=Age_group.value_counts().values,hue=Age_group.value_counts().index)
Age_group.value_counts().plot(ax=axes[1],kind='pie', autopct='%1.1f%%',startangle=90)

plt.tight_layout
plt.show()

"""The dataset is dominated by adult patients, with Older Adults (29.8%) and Young Adults (24.6%) forming the majority. Middle-Aged and Senior groups contribute nearly equal shares, while Children represent only 1.6% of the population. This distribution suggests that chronic and age-related conditions are likely the main drivers of hospital visits to Older Adults and Younger adults.

**Correlation Matrix**:-
Visualize the correlation between all features after encoding to see relationships between variables.
"""

# Correlation Heatmap for numerical features
corr = df.corr(numeric_only=True)
print(corr)
plt.figure(figsize=(10,6))
sns.heatmap(corr, annot=True, linewidths=1)
plt.title("Correlation Heatmap")
plt.show()
